name: "Service Config Validator"
description: "Validates service configuration files"
runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Run PHP Script
      shell: bash  # Adicionei o shell
      run: |
        php app.php