name: "Service Config Validator"
description: "Validates service configuration files"
runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Composer install
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH && composer install

    - name: Run PHP Script
      shell: bash
      run: |
        php $GITHUB_ACTION_PATH/config/boot.php validate